-- 创建 health_archives 表
-- 用于健康档案管理
-- 执行日期: 请在服务器上执行此脚本

-- 创建表
CREATE TABLE IF NOT EXISTS health_archives (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    customer_no VARCHAR(50) NOT NULL,
    channels JSONB DEFAULT '{}',
    basic_info JSONB DEFAULT '{}',
    health_history JSONB DEFAULT '{}',
    subjective_demand TEXT DEFAULT '',
    signature1 JSONB DEFAULT '{}',
    signature2 JSONB DEFAULT '{}',
    footer JSONB DEFAULT '{}',
    status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(id),
    updated_by INTEGER REFERENCES users(id),
    deleted_at TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE
);

-- 创建唯一约束
ALTER TABLE health_archives
ADD CONSTRAINT IF NOT EXISTS health_archives_user_customer_unique
UNIQUE (user_id, customer_no);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_health_archives_user_id ON health_archives(user_id);
CREATE INDEX IF NOT EXISTS idx_health_archives_customer_no ON health_archives(customer_no);
CREATE INDEX IF NOT EXISTS idx_health_archives_status ON health_archives(status);
CREATE INDEX IF NOT EXISTS idx_health_archives_created_at ON health_archives(created_at);
CREATE INDEX IF NOT EXISTS idx_health_archives_is_deleted ON health_archives(is_deleted);

-- 添加注释
COMMENT ON TABLE health_archives IS '健康档案表 - 存储客户健康档案信息';
COMMENT ON COLUMN health_archives.id IS '主键ID';
COMMENT ON COLUMN health_archives.user_id IS '关联的用户ID';
COMMENT ON COLUMN health_archives.customer_no IS '客户编号';
COMMENT ON COLUMN health_archives.channels IS '渠道信息(JSON格式)';
COMMENT ON COLUMN health_archives.basic_info IS '基本信息(JSON格式)';
COMMENT ON COLUMN health_archives.health_history IS '健康史(JSON格式)';
COMMENT ON COLUMN health_archives.subjective_demand IS '主观诉求';
COMMENT ON COLUMN health_archives.signature1 IS '签名1(JSON格式)';
COMMENT ON COLUMN health_archives.signature2 IS '签名2(JSON格式)';
COMMENT ON COLUMN health_archives.footer IS '页脚信息(JSON格式)';
COMMENT ON COLUMN health_archives.status IS '状态(active/inactive等)';
