import { db } from "../src/db";
import { sql } from "drizzle-orm";

async function createMissingTables() {
  console.log('开始创建缺少的表...');

  // 创建 permission_templates 表
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS permission_templates (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name VARCHAR(100) NOT NULL,
      description VARCHAR(255),
      tenant_id BIGINT NOT NULL DEFAULT 1,
      is_system BOOLEAN DEFAULT false,
      is_deleted BOOLEAN DEFAULT false,
      deleted_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      created_by INTEGER REFERENCES users(id),
      updated_by INTEGER REFERENCES users(id),
      CONSTRAINT permission_templates_tenant_name_unique UNIQUE (tenant_id, name)
    );
  `);

  // 创建 template_permissions 表
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS template_permissions (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      template_id INTEGER NOT NULL REFERENCES permission_templates(id) ON DELETE CASCADE,
      permission_id INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
      tenant_id BIGINT NOT NULL DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT template_permission_tenant_unique UNIQUE (tenant_id, template_id, permission_id)
    );
  `);

  // 创建索引
  await db.execute(sql`
    CREATE INDEX IF NOT EXISTS idx_permission_templates_tenant_id ON permission_templates(tenant_id);
  `);

  await db.execute(sql`
    CREATE INDEX IF NOT EXISTS idx_template_permissions_template_id ON template_permissions(template_id);
  `);

  await db.execute(sql`
    CREATE INDEX IF NOT EXISTS idx_template_permissions_permission_id ON template_permissions(permission_id);
  `);

  console.log('✓ 表创建完成！');
  process.exit(0);
}

createMissingTables().catch((error) => {
  console.error('创建表失败:', error);
  process.exit(1);
});
