-- 创建积分系统相关的表

-- 创建枚举类型
DO $$ BEGIN
    CREATE TYPE point_transaction_type AS ENUM ('earn', 'spend', 'expire', 'adjust', 'level_up');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE point_reward_type AS ENUM ('one_time', 'daily', 'streak', 'achievement');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 用户积分表
CREATE TABLE IF NOT EXISTS user_points (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tenant_id BIGINT NOT NULL DEFAULT 1,

    -- 积分相关
    points INTEGER NOT NULL DEFAULT 0,
    total_earned INTEGER NOT NULL DEFAULT 0,
    total_spent INTEGER NOT NULL DEFAULT 0,

    -- 等级相关
    level INTEGER NOT NULL DEFAULT 1,
    experience INTEGER NOT NULL DEFAULT 0,
    next_level_exp INTEGER NOT NULL DEFAULT 50,

    -- 签到相关
    check_in_streak INTEGER DEFAULT 0,
    last_check_in_date VARCHAR(10),
    total_check_in_days INTEGER DEFAULT 0,

    metadata JSONB DEFAULT '{}',
    is_deleted BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    created_by INTEGER REFERENCES users(id),
    updated_by INTEGER REFERENCES users(id)
);

-- 积分流水表
CREATE TABLE IF NOT EXISTS point_transactions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tenant_id BIGINT NOT NULL DEFAULT 1,

    -- 交易信息
    type point_transaction_type NOT NULL,
    amount INTEGER NOT NULL,
    balance INTEGER NOT NULL,

    -- 来源和描述
    source VARCHAR(50),
    description VARCHAR(255),
    reference_id VARCHAR(100),

    -- 经验相关
    experience_gained INTEGER DEFAULT 0,

    status VARCHAR(20) DEFAULT 'completed',
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP DEFAULT NOW()
);

-- 积分奖励配置表
CREATE TABLE IF NOT EXISTS point_rewards (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id BIGINT NOT NULL DEFAULT 1,

    -- 奖励配置
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    type point_reward_type NOT NULL,

    -- 奖励内容
    points INTEGER NOT NULL DEFAULT 0,
    experience INTEGER NOT NULL DEFAULT 0,

    -- 条件限制
    max_daily_times INTEGER DEFAULT 1,
    max_total_times INTEGER DEFAULT 0,

    -- 连续签到配置
    streak_days INTEGER DEFAULT 0,

    is_active BOOLEAN DEFAULT TRUE,
    sort_order INTEGER DEFAULT 0,

    metadata JSONB DEFAULT '{}',
    is_deleted BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    created_by INTEGER REFERENCES users(id),
    updated_by INTEGER REFERENCES users(id),

    UNIQUE(code)
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_user_points_user_id ON user_points(user_id);
CREATE INDEX IF NOT EXISTS idx_user_points_level ON user_points(level);
CREATE INDEX IF NOT EXISTS idx_user_points_check_in_streak ON user_points(check_in_streak);

CREATE INDEX IF NOT EXISTS idx_point_transactions_user_id ON point_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_point_transactions_created_at ON point_transactions(created_at);
CREATE INDEX IF NOT EXISTS idx_point_transactions_type ON point_transactions(type);

CREATE INDEX IF NOT EXISTS idx_point_rewards_tenant_id ON point_rewards(tenant_id);
CREATE INDEX IF NOT EXISTS idx_point_rewards_is_active ON point_rewards(is_active);
CREATE INDEX IF NOT EXISTS idx_point_rewards_is_deleted ON point_rewards(is_deleted);

COMMENT ON TABLE user_points IS '用户积分表';
COMMENT ON TABLE point_transactions IS '积分流水表';
COMMENT ON TABLE point_rewards IS '积分奖励配置表';
